@startuml BeforeTheEvent Use Cases
actor Organizer
usecase "Invite Attendees to Existing Group" as EG
usecase "Invite Attendees to New Group" as NG

actor Attendee
usecase "Join Group" as JG

Organizer --> EG
Organizer --> NG
Attendee --> JG


@enduml