// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TA.Starquest.DataAccess;
using TA.Starquest.DataAccess.EFCore;

namespace TA.Starquest.DataAccess.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20200810163717_InitialSchema")]
    partial class InitialSchema
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedName")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles");

                    b.HasData(
                        new
                        {
                            Id = "1204ca89-ad5a-4e52-af4d-cb9864254e91",
                            ConcurrencyStamp = "98183e7c-570c-4824-bd0f-5b3b1d63e045",
                            Name = "Administrator"
                        },
                        new
                        {
                            Id = "341c4df2-23fe-4905-96f6-0914f73d95e1",
                            ConcurrencyStamp = "3b7bf515-7c9a-4713-ad20-5c7098b3693e",
                            Name = "Moderator"
                        },
                        new
                        {
                            Id = "27b31d46-7f3e-4bc9-a9cc-4718797c12d8",
                            ConcurrencyStamp = "33bd4f49-066e-4f28-97af-3787f4e19d62",
                            Name = "EventManager"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(128)")
                        .HasMaxLength(128);

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(128)")
                        .HasMaxLength(128);

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");

                    b.HasData(
                        new
                        {
                            UserId = "c2e1b3d3-f1cf-4c9b-b712-37502c6e9992",
                            RoleId = "1204ca89-ad5a-4e52-af4d-cb9864254e91"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(128)")
                        .HasMaxLength(128);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(128)")
                        .HasMaxLength(128);

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("TA.Starquest.DataAccess.Entities.Badge", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ImageIdentifier")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Badges");
                });

            modelBuilder.Entity("TA.Starquest.DataAccess.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Artificial Satellite"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Asterism"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Astrometry"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Comet"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Constellation"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Crater"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Dark Nebula"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Diffuse Nebula"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Double Star"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Eclipse"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Emission Nebula"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Galaxy"
                        },
                        new
                        {
                            Id = 13,
                            Name = "Globular Cluster"
                        },
                        new
                        {
                            Id = 14,
                            Name = "Mare"
                        },
                        new
                        {
                            Id = 15,
                            Name = "Meteor"
                        },
                        new
                        {
                            Id = 16,
                            Name = "Minor Planet"
                        },
                        new
                        {
                            Id = 17,
                            Name = "Open Cluster"
                        },
                        new
                        {
                            Id = 18,
                            Name = "Phase"
                        },
                        new
                        {
                            Id = 19,
                            Name = "Phenomenon"
                        },
                        new
                        {
                            Id = 20,
                            Name = "Planet"
                        },
                        new
                        {
                            Id = 21,
                            Name = "Planetary Nebula"
                        },
                        new
                        {
                            Id = 22,
                            Name = "Region"
                        },
                        new
                        {
                            Id = 23,
                            Name = "Satellite"
                        },
                        new
                        {
                            Id = 24,
                            Name = "Sky"
                        },
                        new
                        {
                            Id = 25,
                            Name = "Star"
                        },
                        new
                        {
                            Id = 26,
                            Name = "Surface Feature"
                        },
                        new
                        {
                            Id = 27,
                            Name = "Variable Star"
                        });
                });

            modelBuilder.Entity("TA.Starquest.DataAccess.Entities.Challenge", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("BookSection")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Location")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MissionTrackId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Points")
                        .HasColumnType("int");

                    b.Property<string>("ValidationImage")
                        .IsRequired()
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("MissionTrackId");

                    b.ToTable("Challenges");
                });

            modelBuilder.Entity("TA.Starquest.DataAccess.Entities.Mission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Precondition")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(128)")
                        .HasMaxLength(128);

                    b.HasKey("Id");

                    b.ToTable("Missions");
                });

            modelBuilder.Entity("TA.Starquest.DataAccess.Entities.MissionLevel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AwardTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.Property<int>("MissionId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Precondition")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("MissionId");

                    b.ToTable("MissionLevels");
                });

            modelBuilder.Entity("TA.Starquest.DataAccess.Entities.MissionTrack", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AwardTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("BadgeId")
                        .HasColumnType("int");

                    b.Property<int>("MissionLevelId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Number")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BadgeId");

                    b.HasIndex("MissionLevelId");

                    b.ToTable("MissionTracks");
                });

            modelBuilder.Entity("TA.Starquest.DataAccess.Entities.Observation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ChallengeId")
                        .HasColumnType("int");

                    b.Property<int>("Equipment")
                        .HasColumnType("int");

                    b.Property<string>("ExpectedImage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ObservationDateTimeUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("ObservingSite")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Seeing")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("SubmittedImage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Transparency")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("ChallengeId");

                    b.HasIndex("UserId");

                    b.ToTable("Observations");
                });

            modelBuilder.Entity("TA.Starquest.DataAccess.Entities.ObservingSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("RemindOneDayBefore")
                        .HasColumnType("bit");

                    b.Property<bool>("RemindOneWeekBefore")
                        .HasColumnType("bit");

                    b.Property<int>("ScheduleState")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartsAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Venue")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ObservingSessions");
                });

            modelBuilder.Entity("TA.Starquest.DataAccess.Entities.QueuedWorkItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Disposition")
                        .HasColumnType("int");

                    b.Property<DateTime>("ProcessAfter")
                        .HasColumnType("datetime2");

                    b.Property<string>("QueueName")
                        .IsRequired()
                        .HasColumnType("nvarchar(8)")
                        .HasMaxLength(8);

                    b.HasKey("Id");

                    b.ToTable("QueuedWorkItems");

                    b.HasDiscriminator<string>("Discriminator").HasValue("QueuedWorkItem");
                });

            modelBuilder.Entity("TA.Starquest.DataAccess.Entities.StarquestUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<int?>("ObservingSessionId")
                        .HasColumnType("int");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<DateTime>("Provisioned")
                        .HasColumnType("datetime2");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.HasIndex("ObservingSessionId");

                    b.ToTable("AspNetUsers");

                    b.HasData(
                        new
                        {
                            Id = "c2e1b3d3-f1cf-4c9b-b712-37502c6e9992",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "4c31de8e-f01a-4b1e-b698-8a7abdd5c3a2",
                            Email = "Tim@tigranetworks.co.uk",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "TIM@TIGRANETWORKS.CO.UK",
                            NormalizedUserName = "ADMINISTRATOR",
                            PasswordHash = "AQAAAAEAACcQAAAAEEnDdH/APr8EKDX1oaTusG0SvQFvZk9qJMoDY33pLJHjZdbwEPfXIZ4RlocDvYNFAg==",
                            PhoneNumberConfirmed = false,
                            Provisioned = new DateTime(2020, 8, 10, 16, 37, 16, 162, DateTimeKind.Utc).AddTicks(5517),
                            SecurityStamp = "925d1e02-5fba-47bc-80e6-53d2bcb3fb94",
                            TwoFactorEnabled = false,
                            UserName = "Administrator"
                        });
                });

            modelBuilder.Entity("TA.Starquest.DataAccess.Entities.UserBadge", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("BadgeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Awarded")
                        .HasColumnType("datetime2");

                    b.HasKey("UserId", "BadgeId");

                    b.HasIndex("Awarded");

                    b.HasIndex("BadgeId");

                    b.ToTable("UserBadges");
                });

            modelBuilder.Entity("TA.Starquest.DataAccess.Entities.QueueWorkItems.ObservingSessionCancellation", b =>
                {
                    b.HasBaseType("TA.Starquest.DataAccess.Entities.QueuedWorkItem");

                    b.Property<string>("Message")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ObservingSessionId")
                        .HasColumnType("int");

                    b.HasDiscriminator().HasValue("ObservingSessionCancellation");
                });

            modelBuilder.Entity("TA.Starquest.DataAccess.Entities.QueueWorkItems.ObservingSessionReminder", b =>
                {
                    b.HasBaseType("TA.Starquest.DataAccess.Entities.QueuedWorkItem");

                    b.Property<int?>("ObservingSessionId")
                        .HasColumnType("int");

                    b.HasDiscriminator().HasValue("ObservingSessionReminder");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("TA.Starquest.DataAccess.Entities.StarquestUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("TA.Starquest.DataAccess.Entities.StarquestUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TA.Starquest.DataAccess.Entities.StarquestUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("TA.Starquest.DataAccess.Entities.StarquestUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TA.Starquest.DataAccess.Entities.Challenge", b =>
                {
                    b.HasOne("TA.Starquest.DataAccess.Entities.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TA.Starquest.DataAccess.Entities.MissionTrack", "MissionTrack")
                        .WithMany("Challenges")
                        .HasForeignKey("MissionTrackId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TA.Starquest.DataAccess.Entities.MissionLevel", b =>
                {
                    b.HasOne("TA.Starquest.DataAccess.Entities.Mission", "Mission")
                        .WithMany("MissionLevels")
                        .HasForeignKey("MissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TA.Starquest.DataAccess.Entities.MissionTrack", b =>
                {
                    b.HasOne("TA.Starquest.DataAccess.Entities.Badge", "Badge")
                        .WithMany()
                        .HasForeignKey("BadgeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TA.Starquest.DataAccess.Entities.MissionLevel", "MissionLevel")
                        .WithMany("Tracks")
                        .HasForeignKey("MissionLevelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TA.Starquest.DataAccess.Entities.Observation", b =>
                {
                    b.HasOne("TA.Starquest.DataAccess.Entities.Challenge", "Challenge")
                        .WithMany()
                        .HasForeignKey("ChallengeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TA.Starquest.DataAccess.Entities.StarquestUser", "User")
                        .WithMany("Observations")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TA.Starquest.DataAccess.Entities.StarquestUser", b =>
                {
                    b.HasOne("TA.Starquest.DataAccess.Entities.ObservingSession", null)
                        .WithMany("Attendees")
                        .HasForeignKey("ObservingSessionId");
                });

            modelBuilder.Entity("TA.Starquest.DataAccess.Entities.UserBadge", b =>
                {
                    b.HasOne("TA.Starquest.DataAccess.Entities.Badge", "Badge")
                        .WithMany("UserBadges")
                        .HasForeignKey("BadgeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TA.Starquest.DataAccess.Entities.StarquestUser", "User")
                        .WithMany("UserBadges")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
